# Generated by Django 4.0.3 on 2023-08-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
