# Generated by Django 4.0.3 on 2023-08-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_word_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='url',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
