# Generated by Django 4.2.1 on 2023-08-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MZUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, unique=True)),
                ('generation', models.CharField(max_length=100)),
                ('questions', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('GX', models.IntegerField()),
                ('GY', models.IntegerField()),
                ('GMZ', models.IntegerField()),
            ],
        ),
    ]
