# Generated by Django 4.2.1 on 2023-08-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MZUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, unique=True)),
                ('generation', models.CharField(max_length=100)),
                ('questions', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('left', models.TextField()),
                ('right', models.TextField()),
                ('LGX', models.IntegerField(default=0)),
                ('RGX', models.IntegerField(default=0)),
                ('LGY', models.IntegerField(default=0)),
                ('RGY', models.IntegerField(default=0)),
                ('LGMZ', models.IntegerField(default=0)),
                ('RGMZ', models.IntegerField(default=0)),
                ('Total', models.IntegerField(default=0)),
            ],
        ),
    ]
