# Generated by Django 4.0.3 on 2023-08-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=100)),
                ('Fone', models.CharField(max_length=200)),
                ('Ftwo', models.CharField(max_length=200)),
                ('Fthird', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MZUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, unique=True)),
                ('generation', models.CharField(max_length=100)),
                ('questions', models.JSONField(default=dict)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('left', models.TextField()),
                ('right', models.TextField()),
                ('LGX', models.IntegerField(default=0)),
                ('Plgx', models.IntegerField(default=0)),
                ('RGX', models.IntegerField(default=0)),
                ('Prgx', models.IntegerField(default=0)),
                ('LGM', models.IntegerField(default=0)),
                ('Plgm', models.IntegerField(default=0)),
                ('RGM', models.IntegerField(default=0)),
                ('Prgm', models.IntegerField(default=0)),
                ('LGZ', models.IntegerField(default=0)),
                ('Plgz', models.IntegerField(default=0)),
                ('RGZ', models.IntegerField(default=0)),
                ('Prgz', models.IntegerField(default=0)),
                ('Total', models.IntegerField(default=0)),
            ],
        ),
    ]
