# Generated by Django 4.2.1 on 2023-08-09 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oldmantest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testquestion',
            old_name='LGMZ',
            new_name='LGM',
        ),
        migrations.RenameField(
            model_name='testquestion',
            old_name='LGY',
            new_name='LGZ',
        ),
        migrations.RenameField(
            model_name='testquestion',
            old_name='RGMZ',
            new_name='RGM',
        ),
        migrations.RenameField(
            model_name='testquestion',
            old_name='RGY',
            new_name='RGZ',
        ),
    ]
