# Generated by Django 4.2.1 on 2023-08-03 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oldmantest', '0002_alter_user_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
    ]
