# Generated by Django 4.2.1 on 2023-08-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldmantest', '0002_rename_lgmz_testquestion_lgm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mzuser',
            name='questions',
            field=models.JSONField(verbose_name=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
        ),
    ]
