# Generated by Django 4.2.1 on 2023-08-04 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oldmantest', '0004_mzuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
