# Generated by Django 4.2.1 on 2023-08-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldmantest', '0004_alter_mzuser_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='Plgm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='Plgx',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='Plgz',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='Prgm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='Prgx',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='Prgz',
            field=models.IntegerField(default=0),
        ),
    ]
